In [1]:
!ls

btc_quote.csv		       forum_scraping_optim_loop(deprecated).py
chromedriver		       forum_scraping_optim.py
export.csv		       NLP_Cryptocurrency_Dataset.csv
final_data0-800.csv	       quote_scraping(deprecated).py
final_data15000-15715.csv      README.md
final_data15716-17268.csv      scraping_get_threads_url.py
final_data17269-18539.csv      scraping test(deprecated).py
final_data18540-20000.csv      threads_url.csv
final_data.csv		       Time series.ipynb
forum_scraping(deprecated).py  Untitled.ipynb

In [2]:
import pandas as pd
import numpy as np

### Basic data cleaning and exploration

In [47]:
data = pd.read_csv("NLP_Cryptocurrency_Dataset.csv", header=1, index_col='Unnamed: 0')
data.head()

/home/gauthier/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:395: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

,datetime,id,status,activity,merit,post
0,2018-08-24 07:33:34,Kurisuu9,Jr. Member,38.0,0.0,https://cointelegraph.com/news/kaspersky-lab-n...
1,2018-08-22 21:33:03,sejem,Jr. Member,238.0,2.0,"Every few weeks this summer, bitcoin bulls hav..."
2,2018-08-22 22:14:54,DooMAD,Legendary,1736.0,1136.0,Are people really waiting for an ETF? Or does...
3,2018-08-22 22:32:31,Anarchist,Sr. Member,399.0,250.0,Most people don't care about an ETF and don't ...
4,2018-08-22 22:43:13,erickkyut,Hero Member,854.0,506.0,Everyone is waiting again for the ETF approval...

In [48]:
#data[np.isnan(data['activity'])]

There are 143 cases in which we have not recorded any information about the user, since he was anonymous on the forum. We do not even have the date. Therefore, we choose to remove those marginal cases. We do the same with potential duplicates.

In [49]:
data=data.dropna().drop_duplicates().reset_index(drop=True)

In [50]:
data.describe(include='all')

,datetime,id,status,activity,merit,post
count,1023874,1023874,1023874,1.023874e+06,1.023874e+06,1023874
unique,957253,58769,45,NaN,NaN,1010267
top,24/05/2018 09:12,franky1,Jr. Member,NaN,NaN,
freq,10,3729,206360,NaN,NaN,47
mean,NaN,NaN,NaN,4.527239e+02,2.520218e+02,NaN
std,NaN,NaN,NaN,4.352617e+02,3.415715e+02,NaN
min,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN
25%,NaN,NaN,NaN,1.420000e+02,3.000000e+00,NaN
50%,NaN,NaN,NaN,3.220000e+02,1.000000e+02,NaN
75%,NaN,NaN,NaN,6.300000e+02,3.170000e+02,NaN
max,NaN,NaN,NaN,3.150000e+03,3.413000e+03,NaN

### Data recovery

In the scraping data, we have not included the id of the thread, we would like to access this information. We will therefore try to recover it.

In [51]:
data.head(25)

,datetime,id,status,activity,merit,post
0,2018-08-24 07:33:34,Kurisuu9,Jr. Member,38.0,0.0,https://cointelegraph.com/news/kaspersky-lab-n...
1,2018-08-22 21:33:03,sejem,Jr. Member,238.0,2.0,"Every few weeks this summer, bitcoin bulls hav..."
2,2018-08-22 22:14:54,DooMAD,Legendary,1736.0,1136.0,Are people really waiting for an ETF? Or does...
3,2018-08-22 22:32:31,Anarchist,Sr. Member,399.0,250.0,Most people don't care about an ETF and don't ...
4,2018-08-22 22:43:13,erickkyut,Hero Member,854.0,506.0,Everyone is waiting again for the ETF approval...
5,2018-08-22 23:31:27,xitrum,Member,308.0,10.0,"Quote from: sejem on August 22, 2018, 09:33:03..."
6,2018-08-22 23:42:35,vgk88,Full Member,420.0,124.0,I'm not surprised that ETF rejected. First you...
7,2018-08-23 01:05:58,flowers5,Member,172.0,10.0,The regulators do not have their regulations i...
8,2018-08-23 02:01:32,diceoption.com,Newbie,28.0,0.0,"Waiting again for the ETF approval, BTC will pum"
9,2018-08-23 02:49:53,reactorjuno,Member,210.0,29.0,I'm sorry but how could we have an Exchange Tr...
10,2018-08-23 02:55:14,pooya87,Legendary,1400.0,1158.0,"Quote from: DooMAD on August 22, 2018, 10:14:5..."
11,2018-08-23 03:16:56,dothebeats,Legendary,1582.0,1064.0,No matter how many ETFs are scrutinized and ar...
12,2018-08-23 06:04:42,Pursuer,Legendary,1260.0,1074.0,I agree that the market is becoming more resil...
13,2018-08-23 06:55:31,BlockchainGod,Full Member,280.0,100.0,It seems to me stupid to wait for an ETF. This...
14,2018-08-23 07:07:13,Dr.Osh,Legendary,1064.0,1000.0,"Quote from: BlockchainGod on August 23, 2018, ..."
15,2018-08-23 08:18:21,Lionheart001,Jr. Member,72.0,0.0,Enough of this bullshit. We were doing fine wi...
16,2018-08-23 08:26:31,davhek,Full Member,395.0,100.0,It is almost certain ETFs will not be approved...
17,2018-08-23 08:34:36,talkbitcoin,Legendary,1092.0,1009.0,"i am wondering who these ""bitcoin investors"" a..."
18,2018-08-23 09:23:45,mackenzie5,Jr. Member,159.0,0.0,Bitcoin market source is awaiting from long ba...
19,2018-08-23 10:22:57,bellamente,Member,266.0,10.0,ETF does not affect the price of bitcoin! This...
20,2018-08-23 11:15:07,Jessica2009,Full Member,345.0,100.0,The cryptocurrency community is waiting for ...
21,2018-08-23 11:31:59,Ibizugbe1,Jr. Member,126.0,0.0,I have decided not not be bothered by the cont...
22,2018-08-23 21:19:38,hubballi,Sr. Member,727.0,296.0,"Quote from: markenson12 on August 23, 2018, 09..."
23,2018-08-23 21:26:57,xbossJ,Jr. Member,98.0,0.0,Before ETFs bitcoin was trading rugged and sta...
24,2018-08-23 21:31:18,aoluain,Sr. Member,574.0,268.0,"Quote from: hubballi on August 23, 2018, 09:19..."

In [52]:
data["datetime"]=pd.to_datetime(data["datetime"])
data['datetime_lag']=data['datetime'].shift(1)
#pd.to_datetime(data["datetime_lag"])
data.head()

,datetime,id,status,activity,merit,post,datetime_lag
0,2018-08-24 07:33:34,Kurisuu9,Jr. Member,38.0,0.0,https://cointelegraph.com/news/kaspersky-lab-n...,NaT
1,2018-08-22 21:33:03,sejem,Jr. Member,238.0,2.0,"Every few weeks this summer, bitcoin bulls hav...",2018-08-24 07:33:34
2,2018-08-22 22:14:54,DooMAD,Legendary,1736.0,1136.0,Are people really waiting for an ETF? Or does...,2018-08-22 21:33:03
3,2018-08-22 22:32:31,Anarchist,Sr. Member,399.0,250.0,Most people don't care about an ETF and don't ...,2018-08-22 22:14:54
4,2018-08-22 22:43:13,erickkyut,Hero Member,854.0,506.0,Everyone is waiting again for the ETF approval...,2018-08-22 22:32:31

sub['thread_id']=0
index = 0
for i in range(len(sub)):
    if sub.loc[i]['datetime']>sub.loc[i]['datetime_lag']:
        index +=1
    sub.loc[i]['thread_id'] = index

In [56]:
data['thread_id'] = data['datetime']<data['datetime_lag']

index = 0

def thread_mapping (row):
    global index
    if row['thread_id']:
        index +=1
        temporal = index
        return(temporal)
    else: 
        temporal = index
        return(temporal)
    
thread_id = data.apply(thread_mapping, axis=1)
data['thread_id']=thread_id

In [59]:
data.tail()

,datetime,id,status,activity,merit,post,datetime_lag,thread_id
1023869,2017-01-23 08:38:33,LLec,Hero Member,714.0,500.0,"Quote from: legendbtc on January 21, 2017, 11:...",2017-01-23 08:35:00,21107
1023870,2017-01-23 08:47:19,Taki,Hero Member,882.0,514.0,"Well, don't know to such serious firms as heal...",2017-01-23 08:38:33,21107
1023871,2017-01-23 08:53:00,roadbits,Legendary,1092.0,1000.0,"Quote from: LLec on January 23, 2017, 08:38:33...",2017-01-23 08:47:19,21107
1023872,2017-01-23 08:54:51,Zadicar,Legendary,1050.0,1000.0,I dont think soo that this thing would be impl...,2017-01-23 08:53:00,21107
1023873,2017-01-23 09:09:23,avikz,Legendary,1022.0,1044.0,Accepting bitcoin will be very beneficial for ...,2017-01-23 08:54:51,21107

In [60]:
data.to_csv('data_threads.csv')

## LDA implementation

!pip install stop-words,gensim

In [71]:
sub = data.sample(frac=0.001).reset_index()
sub.head()

,index,datetime,id,status,activity,merit,post,datetime_lag,thread_id
0,126231,2017-11-04 13:35:51,mikaeltomcruz12,Full Member,308.0,100.0,It help people having easy way of online payme...,2017-11-04 13:31:40,829
1,576836,2017-05-29 00:49:32,riphunter,Full Member,168.0,100.0,Paypal will be hard to compete with bitcoin be...,2017-05-29 00:45:46,5628
2,679148,2017-06-18 15:54:12,bitlifter,Newbie,3.0,0.0,"Bitcoin as a currency, is accepted and identif...",2017-06-18 15:50:58,6900
3,249355,2018-06-13 09:48:00,louis sean,Jr. Member,94.0,0.0,This is not new and not surprising news. Boliv...,2018-06-13 09:31:00,3191
4,657465,2017-11-01 20:05:53,eaLiTy,Hero Member,868.0,504.0,"Quote from: kafiddrhman on November 01, 2017, ...",2017-11-01 19:49:32,6537

In [73]:
post_by_thread = data.groupby('thread_id')['post'].apply(lambda x: "{%s}" % ', '.join(x))

In [81]:
from nltk.tokenize import RegexpTokenizer
from stop_words import get_stop_words
from nltk.stem.porter import PorterStemmer
from gensim import corpora, models
import gensim
import progressbar

tokenizer = RegexpTokenizer(r'\w+')

# create English stop words list
en_stop = get_stop_words('en')

# Create p_stemmer of class PorterStemmer
p_stemmer = PorterStemmer()
    
# list for tokenized documents in loop
texts = []

# loop through document list
for i in progressbar.progressbar(post_by_thread):
    
    # clean and tokenize document string
    raw = i.lower()
    tokens = tokenizer.tokenize(raw)

    # remove stop words from tokens
    stopped_tokens = [i for i in tokens if not i in en_stop]
    
    # stem tokens
    stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]
    
    # add tokens to list
    texts.append(stemmed_tokens)

# turn our tokenized documents into a id <-> term dictionary
dictionary = corpora.Dictionary(texts)
    
# convert tokenized documents into a document-term matrix
corpus = [dictionary.doc2bow(text) for text in texts]

100% (21108 of 21108) |##################| Elapsed Time: 0:29:20 Time:  0:29:20

In [83]:
# generate LDA model
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics=50, id2word = dictionary, passes=20)